name: CI


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build docker image
        run: docker build -t aelshamy/docker-react .
      #- name: Run tests
       # run: docker run -e CI=true aelshamy/docker-react npm run test
      - name: Beanstalk Deploy
        uses: einaregilsson/beanstalk-deploy@v13
        with:
          aws_access_key: ${{secrets.AWS_ACCESS_KEY}}
          aws_secret_key: ${{secrets.AWS_SECRET_KEY}}
          region: "us-east-1"
          application_name: "docker-react"
          environment_name: "DockerReact-env"
          version_label: "my-app-${{ steps.format-time.outputs.replaced }}"
      - name: Deployed successfully!
        run: echo App deployed to ELB
